# Generated by Django 2.1.5 on 2019-08-28 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_classroom_teacer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom',
            old_name='teacer',
            new_name='teacher',
        ),
    ]
