# Generated by Django 2.1.5 on 2019-08-29 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_auto_20190828_1532'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('name', '-exam_grade')},
        ),
    ]
